# repo:     alexlogvin/.github
# filename: FUNDING.YML

github:             alexlogvin
patreon:            alexlogvin
#open_collective:    open_collective_username
ko_fi:              alexlogvin
#tidelift:           tidelift_package_name
community_bridge:   alexlogvin
liberapay:          alexlogvin
issuehunt:          alexlogvin
#otechie:            otechie_username
#custom:             ["custom_url.com", "another_custom_url.com"]
